import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/NavigationBar.jsx";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EShoping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   suppressHydrationWarning={true}
        className=""
      >


       <header>
        {/* <NavigationBar/> */}
       </header>


        <main className=" container mx-auto mb-9">

          <CartProvider>
          {children}
        </CartProvider>
        </main>


        <footer>
            <Footer/>
        </footer>

        
      </body>
    </html>
  );
}
